coverage:
  round: up
  precision: 1
  status:
    project:
      default:
        threshold: 1%

codecov:
  notify:
    wait_for_ci: true

ignore:
  - "facilyst/utils/dataset_utils"
  - "facilyst/tests/dataset_tests"