name: Check Latest Dependencies

on:
  pull_request:
    types: [ opened, synchronize ]
  schedule:
      - cron: '*/2 * * * *'

jobs:
  update-deps:
    if: github.repository_owner == 'Parthiv-Naresh'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8.x'
      - name: Update Dependencies
        run: |
          python -m pip install .[test]
          export ALLOWED_DEPENDENCY_FILEPATH=../facilyst/requirements.txt
          export LATEST_DEPENDENCY_FILEPATH=facilyst/tests/dependency_tests/latest_dependencies.txt
          facilyst/tests/dependency_tests/dependency_diff.sh
          cat facilyst/tests/dependency_tests/latest_dependencies.txt
      - name: Update Extra Dependencies
        run: |
          python -m pip install .[test]
          python -m pip install .[extra]
          export ALLOWED_DEPENDENCY_FILEPATH=../facilyst/extra-requirements.txt
          export LATEST_DEPENDENCY_FILEPATH=facilyst/tests/dependency_tests/latest_extra_dependencies.txt
          facilyst/tests/dependency_tests/dependency_diff.sh
          cat facilyst/tests/dependency_tests/latest_extra_dependencies.txt
          echo "=============================================="
          ls
          cd ..
          echo "=============================================="
          ls
          cd ..
          echo "=============================================="
          rm -r ./facilyst/facilyst.egg-info
          rm -r ./facilyst/build
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.DEPENDENCY_TOKEN }}
          commit-message: Updated latest dependencies
          title: Update Latest Dependencies
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          body: "This is an auto-generated PR with the latest dependency updates."
          branch: update_latest_dependencies
          branch-suffix: short-commit-hash
          delete-branch: true
          base: main
          assignees: Parthiv-Naresh