name: Unit Tests - Linux

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  unit_tests:
    name: ${{ matrix.python_version }} ${{ matrix.command }} Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "3.9", "3.10"]
        command: ["Graphs", "Mocks", "Models", "Preprocessors", "Utils"]
    steps:
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 2
      - name: Build Facilyst Package
        run: make package_facilyst
      - name: Installing Dependencies
        run: |
          python -m pip install -e unpacked_sdist/
          python -m pip install -e unpacked_sdist/[test]
          pip freeze
      - name: Erase Coverage
        run: |
          python -m pip install "$(cat setup.cfg | grep codecov)"
          coverage erase
          cd unpacked_sdist
          coverage erase
      - if: ${{ matrix.command == 'Graphs' }}
        name: Running Graphs Tests
        run: |
          cd unpacked_sdist
          make test-graphs
      - if: ${{ matrix.command == 'Mocks' }}
        name: Running Mocks Tests
        run: |
          cd unpacked_sdist
          make test-mocks
      - if: ${{ matrix.command == 'Models' }}
        name: Running Models Tests
        run: |
          cd unpacked_sdist
          make test-models
      - if: ${{ matrix.command == 'Preprocessors' }}
        name: Running Preprocessors Tests
        run: |
          cd unpacked_sdist
          make test-preprocessors
      - if: ${{ matrix.command == 'Utils' }}
        name: Running Utils Tests
        run: |
          cd unpacked_sdist
          make test-utils
      - name: Upload pytest duration artifact
        uses: actions/upload-artifact@v2
        with:
          name: pytest-duration-report
          path: test-reports/${{matrix.command}}-junit.xml
      - name: install coverage
        run: pip install coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

