name: Release Notes Updated

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore:
      - '**update_latest_dependencies-**'

jobs:
  release_notes_updated:
    name: Release Notes Updated
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Release notes added
        run: |
          cat docs/release_notes.rst | grep ":pr:\`${{ github.event.number }}\`"
